### ISSUE TITLE
packetsReceived function of PacketLiveStream operator always returns 0

### ISSUE THREAD

**Issue by GudrunKa** [IBMStreams/streamsx.network#109]
When testing the sample livePacketLiveSourceFull the PacketLiveStream operator receives packages, but the parameter packetsReceived in the debug output file is always 0:
"0.0264561176300049,{packetsReceived=0,packetsDropped=0,packetsProcessed=1"

It also does not work if metrics is on.

This might be an error in the packetsReceived function.

**Comment by ejpring** [comment]
I think this issue refers to the PacketLiveSource operator and the LivePacketLiveSourceFull.spl sample application. The packetsReceived() function works properly.

Please note the documentation for the packetsReceived() function:

This function returns the number of packets received from the network interface
since the operator started, **as of the most recent metrics interval, if there is one, or zero if not**.
( from http://ibmstreams.github.io/streamsx.network/doc/spldoc/html/tk$com.ibm.streamsx.network/fc$com.ibm.streamsx.network.source.html )

The LivePacketLiveSourceFull.spl sample application sets the metrics interval to 1.0 seconds, so the packetsReceived() function returns 0 for the first second, then non-zero for the remaining 9 seconds of the test. For example, the last line of the 'debug.LivePacketLiveSourceFull.PacketStream.out' file will be something like this:

0.039233922958374,{packetsReceived=1041,packetsDropped=269,packetsProcessed=890,bytesProcessed=1196215,metricsIntervalElapsed=1.00011992454529,metricsIntervalPacketsReceived=339,metricsIntervalPacketsDropped=269,metricsIntervalPacketsProcessed=70,metricsIntervalBytesProcessed=135480,metricsUpdated=false,CAPTURE_SECONDS=1495715623,CAPTURE_MICROSECONDS=665453,...
