### ISSUE TITLE
obscureIPAddress addition to the new toolkit version

### ISSUE THREAD

**Issue by apyasic** [IBMStreams/streamsx.network#60]
An old toolkit version (com.ibm.streamsx.network.packet) contained very useful function for IP address obscuring. The issue proposes to migrate _obscureIPAddress_ function to the new toolkit version.

**Comment by ejpring** [comment]
I recommend that you remove the obscureIPaddress() function from production code. It was implemented only as a temporary measure for an early Streams application, and provides no security, since it is trivial to decode.

Instead, I recommend changing tuple attributes that are currently assigned with obscureIPaddress() from type 'rstring' to type 'uint32' and assign IP addresses to them as binary values. This will improve runtime performance while still obscuring IP addresses in logs and traces.

**Comment by apyasic** [comment]
Thanks!
