### ISSUE TITLE
Replace the deprecated SPLLOG macro with SPLAPPTRC

### ISSUE THREAD

**Issue by markheger** [IBMStreams/streamsx.network#70]
In C++ primitive operator the SPLLOG macro is used for traces. It should be replaced with SPLAPPTRC since SPLLOG is deprecated and the name LOG is confusing since it produces traces.

**Comment by ejpring** [comment]
I merged these changes into the master branch. However, for the record, I have to say that the confusion here is not between the 'SPLLOG' and 'SPLAPPTRC' macros, its between 'log' and 'trace' files. The distinction isn't really necessary.

**Comment by ejpring** [comment]
Note that there are several new operators for this toolkit in development. They are currently stored in this fork:

https://github.com/ejpring/streamsx.network

The fork also contains lots of small changes to the old operators. I've merged your SPLLOG-> SPLAPPTRC changes into the fork, since there were only a few conflicts. If you plan to make major changes, please coordinate them with Dave and myself.

**Comment by markheger** [comment]
reopen for missing changes in operators:
DNSPacketLiveSource, DNSPacketFileSource, DNSPacketDPDKSource
