### ISSUE TITLE
LivePacketContentAssembler prerequisites and execution in V4.2. QSE 

### ISSUE THREAD

**Issue by GudrunKa** [IBMStreams/streamsx.network#76]
The LivePacketContentAssembler sample requires the com.ibm.iss.pam library from IBM X-Force which is not delivered with the toolkit and cannot be found in intranet. From where can it be retrieved?
The job cannot be started in StreamsStudio without specific privileges (canSetPeOSCapabilities and runAsUser) which also requires that the domain service on the host runs as system services. But that's not possible in the Streams QSE with embeddedzk.
The job can be executed from command line, i.e. with the sample specific script, although the 'static-link' option is no more supported in Streams 4.2. But the script has to be adapted to the directory structure of the product where the 'sample' and the 'toolkit' directory are under the version directory. These points should be documented and corrected respectively, so that the sample works without expensive investigation.

**Comment by ejpring** [comment]
The PAM library is packaged and distributed separately from the network toolkit because it is covered by a different licensing agreement. Please contact me via email at 'pring@us.ibm.com' if you or your customer need this package.

Also, please note that the LivePacketContentAssembler and PAM library can only re-assemble network traffic that is routed to the machine where Streams runs. They are typically used in conjunction with configuration changes to network routers that mirror traffic destined for other machines to Streams. This requires administrator privileges on the routers as well as root privileges on the Streams machine.

**Comment by GudrunKa** [comment]
Since the network toolkit is part of the product, all this should be documented in the spldoc/KC and no mail address should be mentioned there because this could change over time.
