### ISSUE TITLE
Scripts for sample execution do not work with directory structure of the Streams product

### ISSUE THREAD

**Issue by GudrunKa** [IBMStreams/streamsx.network#80]
The scripts for the execution of the samples only fit to the directory structure of the public github, but not to the structure of the Streams product installation. This should be adapted to support both environments.

**Comment by markheger** [comment]
Since there is neither a Makefile nor a Studio build config provided with the samples, it would be fair to prepare the scripts of the samples for Studio workspaces, e.g. imported by copy into a workspace.

The directory structure of the git repository, the Streams installation and the Studio workspace should be concerned.
For example:
[[ -f $STREAMS_INSTALL/toolkits/com.ibm.streamsx.network/info.xml ]] && toolkitDirectory=$STREAMS_INSTALL/toolkits
[[ -f $here/../../../../toolkits/com.ibm.streamsx.network/info.xml ]] && toolkitDirectory=$( cd $here/../../../../toolkits ; pwd )
[[ -f $here/../../../com.ibm.streamsx.network/info.xml ]] && toolkitDirectory=$( cd $here/../../.. ; pwd )
[[ $toolkitDirectory ]] || die "sorry, could not find 'toolkits' directory" 

[[ -f $STREAMS_INSTALL/samples/com.ibm.streamsx.network/SampleNetworkToolkitData/info.xml ]] && sampleDirectory=$STREAMS_INSTALL/samples
[[ -f $here/../../SampleNetworkToolkitData/info.xml ]] && sampleDirectory=$( cd $here/../.. ; pwd )
[[ $sampleDirectory ]] || die "sorry, could not find 'samples' directory"

**Comment by ejpring** [comment]
I'm not sure I understand your comment. If samples are copied into an Eclipse workspace, they have the same directory structure as the GitHub repository, regardless of where they are copied from, don't they? If so, the speculative directory probes in testPacketFileSourceXxxxxxx.sh should work for samples copied into Studio.
